name: WordPress and PHP Matrix Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        wordpress_version: [6.4, 6.3]
        php_version: [8.3, 8.2, 8.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2