name: WordPress and PHP Matrix Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        wordpress_version: [6.4]
        php_version: [8.3]

    name: PHP ${{ matrix.php_version }} Test on ${{ matrix.wordpress_version}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MySQL
        run: sudo apt-get install -y mysql-server
      - run: |
          sudo /etc/init.d/mysql start
      - name: Set up PHP and WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mbstring, zip, intl

      - name: Check PHP Version
        run: php -v

      - name: Install Composer dependencies
        run: composer install

      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh wordpress_test root '' localhost

      - name: Run tests
        run: ./vendor/bin/phpunit
